[versions]
# Plugins
lombok = "8.14"
shadow = "9.0.0-rc3"
runTask = "2.3.1"
idea = "1.2"
slimjar = "2.1.7"

# Cancer
fukkit = "23.6.1"
amulet = "23.5.1"
chrono = "22.9.10"
spatial = "22.11.2"

velocity = "3.4.0-SNAPSHOT"
spigot = "1.20.2-R0.1-SNAPSHOT"
platformUtils = "e17ac2c698"

# Dynamically Loaded
adventure-api = "4.24.0" # https://github.com/KyoriPowered/adventure
adventure-platform = "4.4.1" # https://github.com/KyoriPowered/adventure-platform

lettuce = "6.5.1.RELEASE"
particle = "1.8.4"
ultimateAdvancementApi = "2.7.1"
customBlockData = "2.2.3"
lur = "1.4.2"
lang3 = "3.12.0"
effectLib = "10.4"
gson = "2.10.1"
fastutil = "8.5.13"
glowingentities = "1.4.9"
caffeine = "3.0.6"

[libraries]
fukkit = { module = "com.github.VolmitDev:Fukkit", version.ref = "fukkit" }
amulet = { module = "com.github.VolmitDev:Amulet", version.ref = "amulet" }
chrono = { module = "com.github.VolmitDev:Chrono", version.ref = "chrono" }
spatial = { module = "com.github.VolmitDev:Spatial", version.ref = "spatial" }

velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
platformUtils = { module = "com.github.CrazyDev05:PlatformUtils", version.ref = "platformUtils" }

adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-api" }
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure-api" }
adventure-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure-api" }
adventure-platform = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }

lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
particle = { module = "xyz.xenondevs:particle", version.ref = "particle" }
ultimateAdvancementApi = { module = "com.frengor:ultimateadvancementapi-shadeable", version.ref = "ultimateAdvancementApi" }
customBlockData = { module = "com.jeff-media:custom-block-data", version.ref = "customBlockData" }
lur = { module = "com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru", version.ref = "lur" }
lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "lang3" }
effectLib = { module = "com.elmakers.mine.bukkit:EffectLib", version.ref = "effectLib" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
glowingentities = { module = "fr.skytasul:glowingentities", version.ref = "glowingentities" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runTask" }
runVelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runTask" }
idea = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea" }
slimjar = { id = "de.crazydev22.slimjar", version.ref = "slimjar" }